title: txt.less
author: Paul Radzkov
email: radzkov@gmail.com
description: > # this means to ignore newlines
  Responsive classnames generator for text alignment.
# twitter_username: paul_radzkov
github_username: paulradzkov
google_analytics: UA-29416794-1
remote_theme: paulradzkov/docs-template
github_link: https://github.com/paulradzkov/txt.less
